### ISSUE TITLE
grayout.vim create a vertical bar on the left?

### ISSUE THREAD

**Issue by NichtsHsu** [mphe/grayout.vim#11] opened 2021-08-16 02:55 UTC
What is it used for and how can I remove it?

![image](https://user-images.githubusercontent.com/35688135/129505325-6c7faa80-5923-4e68-aa51-79ef99b81b93.png)

**Comment by mphe** [comment] 2021-08-16 11:47
Duplicate of #6.
You can use `set signcolumn=no` to hide it. However, usually you also have syntax checkers or other plugins that use the sign column to place signs, so in the end, it doesn't make a difference.

**Closed** 2021-08-16 11:48 UTC

**Comment by NichtsHsu** [comment] 2021-08-16 12:22
@mphe Thx, it works well.

> usually you also have syntax checkers or other plugins that use the sign column to place signs, so in the end, it doesn't make a difference

No, I'm a Linux kernel developer for ARM platform, never use any syntax checkers because they cannot work totally.

**Comment by mphe** [comment] 2021-08-16 12:25
Just out of curiosity, what exactly has the language syntax and a corresponding syntax checker to do with the platform you're developing for?

**Comment by NichtsHsu** [comment] 2021-08-16 13:23
It maybe my impatience to learn the usage. What I am doing: get a new device xxxx, create a driver file xxxx.c under `LINUX/android/kernel/msm-4.9/drivers`, write driver code, then modify Kconfig and Makefile to enable my driver. Almost all syntax checkers warned me unable to find `linux/init.h`, even I added `LINUX/android/kernel/msm-4.9/include` to their configs, they also unabled to find files included by `linux/init.h`. Finally I give up all synatx checkers.

**Comment by mphe** [comment] 2021-08-16 13:46
Ah. You might need more than just an include path. You can use `bear` to generate a `compile_commands.json` from your Makefile (maybe there are even better ways to get a `compile_commands.json` when working on linux kernels). It will include all required build flags so that any code completer and syntax checker should be able to provide proper results.

**Comment by NichtsHsu** [comment] 2021-08-17 02:38
Following the tutorial I executed `make clean && bear make` and generated `compile_commands.json` successfully. Then I tried the `YouCompleteMe` but also `linux/init.h file not find [pp_file_not_found]`. What's worse, `Grayout` became broken, when I call `GrayoutUpdate`, the message was:

```
Error detected while processing function grayout#UpdateGrayout[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nihil/.vim/plugged/grayout.vim/autoload/../python/grayout.py", line 41, in grayout
    filename, args = utils.get_current_args()
  File "/home/nihil/.vim/plugged/grayout.vim/autoload/../python/utils.py", line 63, in get_current_args
    args, cwd = load_compilation_database(filename, dirname)
  File "/home/nihil/.vim/plugged/grayout.vim/autoload/../python/utils.py", line 96, in load_compilation_database
    cmd: cindex.CompileCommand = db.getCompileCommands(filename)[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by NichtsHsu** [comment] 2021-08-17 03:19
It is difficult to config it...However, I always need use `source build/envsetup.sh && lunch xxx-userdebug` to get the full compiling enviroments before `make`, those imformations are what I cannot provide to vim plugins (so they always try to use my system's compiler to build and generate their databases, and obviously be failed).

**Comment by NichtsHsu** [comment] 2021-08-17 04:05
I tried the `YouCompleteMe` but `clangd` seems unable to handle cross-platform flags from `compile_commands.json`. This file looks like (use `$(xxxxxx)` instead of my device):

```
[
...
    {
        "command": "cc -c -Wp,-MD,drivers/input/misc/.$(xxxxxx).o.d -nostdinc -isystem /home/nihil/harddisk/Projects/Avigator/LINUX/android/vendor/qcom/proprietary/llvm-arm-toolchain-ship/8.0/lib/clang/8.0.12/include -I/home/nihil/harddisk/Projects/Avigator/LINUX/android/kernel/msm-4.9/arch/arm64/include -I/home/nihil/harddisk/Projects/Avigator/LINUX/android/out/target/product/sdm710/obj/kernel/msm-4.9/arch/arm64/include/generated/uapi -I/home/nihil/harddisk/Projects/Avigator/LINUX/android/out/target/product/sdm710/obj/kernel/msm-4.9/arch/arm64/include/generated -I/home/nihil/harddisk/Projects/Avigator/LINUX/android/kernel/msm-4.9/include -I/home/nihil/harddisk/Projects/Avigator/LINUX/android/out/target/product/sdm710/obj/kernel/msm-4.9/include -I/home/nihil/harddisk/Projects/Avigator/LINUX/android/kernel/msm-4.9/arch/arm64/include/uapi -I/home/nihil/harddisk/Projects/Avigator/LINUX/android/kernel/msm-4.9/include/uapi -I/home/nihil/harddisk/Projects/Avigator/LINUX/android/out/target/product/sdm710/obj/kernel/msm-4.9/include/generated/uapi -include /home/nihil/harddisk/Projects/Avigator/LINUX/android/kernel/msm-4.9/include/linux/kconfig.h -I/home/nihil/harddisk/Projects/Avigator/LINUX/android/kernel/msm-4.9/drivers/input/misc -I/home/nihil/harddisk/Projects/Avigator/LINUX/android/out/target/product/sdm710/obj/kernel/msm-4.9/drivers/input/misc -D__KERNEL__ -Qunused-arguments -mlittle-endian -Qunused-arguments -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -Wno-unused-variable -Wno-format-invalid-specifier -Wno-gnu -Wno-address-of-packed-member -Wno-duplicate-decl-specifier -Wno-undefined-optimized -Wno-tautological-constant-out-of-range-compare -Wno-sometimes-uninitialized -Wno-asm-operand-widths -Wno-initializer-overrides -fno-builtin -Wno-tautological-compare -mno-global-merge --target=aarch64-linux-gnu --prefix=/home/nihil/harddisk/Projects/Avigator/LINUX/android/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/ --gcc-toolchain=/home/nihil/harddisk/Projects/Avigator/LINUX/android/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -no-integrated-as -Werror=unknown-warning-option -fno-PIE -mno-implicit-float -DCONFIG_AS_LSE=1 -fno-asynchronous-unwind-tables -fno-pic -Wno-asm-operand-widths -fno-delete-null-pointer-checks -Wno-address-of-packed-member -O2 --param=allow-store-data-races=0 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-format-invalid-specifier -Wno-gnu -Wno-duplicate-decl-specifier -Wno-tautological-compare -mno-global-merge -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -pg -Wdeclaration-after-statement -Wno-pointer-sign -Wno-array-bounds -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Wno-initializer-overrides -Wno-unused-value -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-uninitialized -DKBUILD_BASENAME=\\\"$(xxxxxx)\\\" -DKBUILD_MODNAME=\\\"$(xxxxxx)\\\" -o drivers/input/misc/.tmp_$(xxxxxx).o /home/nihil/harddisk/Projects/Avigator/LINUX/android/kernel/msm-4.9/drivers/input/misc/$(xxxxxx).c",
        "directory": "/home/nihil/harddisk/Projects/Avigator/LINUX/android/out/target/product/sdm710/obj/kernel/msm-4.9",
        "file": "/home/nihil/harddisk/Projects/Avigator/LINUX/android/kernel/msm-4.9/drivers/input/misc/$(xxxxxx).c"
    },
...
]
```

**Comment by NichtsHsu** [comment] 2021-08-17 05:00
Anyway, thanks for your advices.
