### ISSUE TITLE
Does grayout.vim support GCC?

### ISSUE THREAD

**Issue by wangrongwei** [mphe/grayout.vim#10] opened 2020-12-21 16:47 UTC
Hi
I have tried to use this script in my vim file, using it helps me read the Linux kernel easily.
But, It seems NOT support the compile_commands.json generated by GCC, is really?

Regards,
Rongwei Wang

**Comment by mphe** [comment] 2020-12-21 16:51
There should be no problem.
What does not work exactly?
How did you generate your compile_commands.json? Also make sure it is in your project root.

**Comment by wangrongwei** [comment] 2020-12-22 02:00
When I press F5, it prints below log:
`Loading libclang: <CDLL 'libclang.so', handle 1011b710 at 0xffff7b490518>
Initialized
Querying arguments for /mnt/nvme8n1/wrw/mainline/linux/mm/memory.c
Searching /mnt/nvme8n1/wrw/mainline/linux/mm/compile_commands.json
Searching /mnt/nvme8n1/wrw/mainline/linux/compile_commands.json
Found config file /mnt/nvme8n1/wrw/mainline/linux/compile_commands.json
CompilationDatabase loaded and stored in cache
/mnt/nvme8n1/wrw/mainline/linux /mnt/nvme8n1/wrw/mainline/linux/mm/memory.c
Compile flags: ['gcc', '-Wp,-MMD,mm/.memory.o.d', '-nostdinc', '-isystem', '/usr/lib/gcc/aarch64-redhat-linux/9/include', '-I./arch/arm64/include', '-I./arch/arm64/include/generated', '-I./include', '-I./arch/arm64/include/uapi', '-I./arch/arm64/include/generated/uapi', '-I./include/uapi', '-I./include/generated/uapi
', '-include', './include/linux/kconfig.h', '-include', './include/linux/compiler_types.h', '-D__KERNEL__', '-mlittle-endian', '-DCC_USING_PATCHABLE_FUNCTION_ENTRY', '-DKASAN_SHADOW_SCALE_SHIFT=3', '-fmacro-prefix-map=./=', '-Wall', '-Wundef', '-Werror=strict-prototypes', '-Wno-trigraphs', '-fno-strict-aliasing', '-f
no-common', '-fshort-wchar', '-fno-PIE', '-Werror=implicit-function-declaration', '-Werror=implicit-int', '-Werror=return-type', '-Wno-format-security', '-std=gnu89', '-mgeneral-regs-only', '-DCONFIG_CC_HAS_K_CONSTRAINT=1', '-Wno-psabi', '-mabi=lp64', '-fno-asynchronous-unwind-tables', '-fno-unwind-tables', '-mbranch
-protection=none', '-Wa,-march=armv8.4-a', '-DARM64_ASM_ARCH="armv8.4-a"', '-DKASAN_SHADOW_SCALE_SHIFT=3', '-fno-delete-null-pointer-checks', '-Wno-frame-address', '-Wno-format-truncation', '-Wno-format-overflow', '-Wno-address-of-packed-member', '-O2', '--param=allow-store-data-races=0', '-Wframe-larger-than=2048',
'-fstack-protector-strong', '-Wno-unused-but-set-variable', '-Wimplicit-fallthrough', '-Wno-unused-const-variable', '-fno-omit-frame-pointer', '-fno-optimize-sibling-calls', '-g', '-gdwarf-4', '-fpatchable-function-entry=2', '-fno-inline-functions-called-once', '-Wdeclaration-after-statement', '-Wvla', '-Wno-pointer-
sign', '-Wno-stringop-truncation', '-Wno-array-bounds', '-Wno-stringop-overflow', '-Wno-restrict', '-Wno-maybe-uninitialized', '-fno-strict-overflow', '-fno-stack-check', '-fconserve-stack', '-Werror=date-time', '-Werror=incompatible-pointer-types', '-Werror=designated-init', '-Wno-packed-not-aligned', '-mstack-prote
ctor-guard=sysreg', '-mstack-protector-guard-reg=sp_el0', '-mstack-protector-guard-offset=1432', '-DKBUILD_MODFILE="mm/memory"', '-DKBUILD_BASENAME="memory"', '-DKBUILD_MODNAME="memory"']
Error parsing translation unit.` 

I just use ./scripts/clang-tools/gen_compile_commands.py (linux kernel own) to generate compile_commands.json, and I'm sure it is in my project root. 

Thanks.

**Comment by mphe** [comment] 2020-12-22 02:58
Alright, I'll look into it and try to reproduce this. There's probably some flag in there that libclang doesn't like for some reason.

**Comment by mphe** [comment] 2020-12-23 19:30
Could you upload your `compile_commands.json`? Saves me some time.

**Comment by wangrongwei** [comment] 2020-12-24 03:40
Of course, enen, and how to upload? Insert code?

**Comment by wangrongwei** [comment] 2020-12-24 04:57
Hi, this is my compile_commands.json:
[compile_commands.txt](https://github.com/mphe/grayout.vim/files/5738151/compile_commands.txt)

Thanks

**Comment by mphe** [comment] 2020-12-28 17:51
I tried to reproduce this using the latest stable linux 5.10 kernel with default configuration, but without "success". Everything seems to work for me. libclang throws some errors, but does not fail like in your case.

Which kernel and config are you using? Please post a download link and your .config file.

**Comment by wangrongwei** [comment] 2020-12-29 02:10
Maybe the problem is I used arm64 arch?
The .config is arch/arm64/configs/defconfig

**Comment by mphe** [comment] 2020-12-29 14:42
> Maybe the problem is I used arm64 arch?

Well I also tried to reproduce it with your compile_commands.json (with adapted paths obviously), and it worked, too.
What version of clang do you have installed (`clang --version`)?

Please post a download link to the exact kernel sources you are working with and the commands you use for setting up your configs.

**Comment by wangrongwei** [comment] 2020-12-30 16:14
This is my clang version:
`clang version 7.0.1 (Red Hat 7.0.1-9.3)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin`

> Please post a download link to the exact kernel sources you are working with

It's also linux-5.10 stable mainline.

> the commands you use for setting up your configs

Sorry, your meaning is what's my commands to compile kernel? maybe following is you want:

`1: cp arch/arm64/configs/defconfig .config`
`2: make`

I will try again. It's very likely that I have a problem in using grayout.vim.
Can you post a screenshot that grayout.vim works？Maybe it will help me.

Thanks:-)

**Comment by wangrongwei** [comment] 2020-12-30 17:22
Hi, mphe
It works, the main problem is grayout.vim is not support the compile_commands.json when the compiler is  gcc. Finally, I compiling all source code using clang:

`make -j$(nproc) CC=clang all compile_commands.json`

Thanks very much~

**Comment by mphe** [comment] 2020-12-30 17:48
Could have been an edge case where clang fails to maintain compatiblity with gcc. Usually it shouldn't matter to libclang if there's gcc or clang in your compile_commands.jsosetupn.
And I probably couldn't reproduce this due to not using an arm64 toolchain like you.

Anyway, since you found a workaround, I'll close the issue.

**Closed by mphe** 2020-12-30 17:48 UTC
